<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property string|null $add_date
 * @property string|null $seo_url
 * @property integer|null $status
 */
class News extends \yii\db\ActiveRecord
{

    public $langs;
    public $main_img;
//    public $sub_header_img;
//    public $catList;
    public $curentLang;
//    public $modelsItems;
//    public $servicesIds = [];


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'news';
    }

    public function behaviors()
    {
        $this->curentLang = Lang::find()->where(['prefix'=>Yii::$app->language])->one();
        return [
            'image' => [
//				'class' => 'rico\yii2images\behaviors\ImageBehave',
                'class' => 'common\lib\costarico_mod\ImageBehaveModifed',
            ]
        ];
    }

    public function getTexts(){
        return $this->hasOne(NewsLang::className(),['news_id' => 'id'])
            ->andOnCondition(['lang_id' => $this->curentLang->id]);
    }

    public function getTextsaray(){
        return $this->hasMany(NewsLang::className(),['news_id' => 'id'])->asArray()->indexBy('lang_id');
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['add_date', 'main_img', 'langs'], 'safe'],
            [['seo_url'], 'string', 'max' => 255],
            [['seo_url'], 'unique'],
            [['status'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'add_date' => Yii::t('app', 'Дата добавления'),
            'seo_url' => Yii::t('app', 'ЧПУ'),
            'status' => Yii::t('app', 'Пкбликацыя'),
        ];
    }

    public function beforeSave($insert)
    {
//        debug($this->langs[$this->curentLang->id]['title']);die();
        if($this->seo_url == ''){
            $seo_url = mb_strtolower($this->langs[$this->curentLang->id]['title']);
            $seo_url = str_replace(['\\','/','\'','?',':','$',',','.','@','"','*','!','#','№','(',')','^',';','_','=','+','`'],'',$seo_url);
            $seo_url = str_replace([' '],'-',$seo_url);
            $exist = self::find()->where(['like', 'seo_url', $seo_url])->count();
            if($exist > 0){
                $seo_url = $seo_url.'-'.($exist+1);
            }
            $this->seo_url = cyr_to_lat($seo_url);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $langs = Lang::find()->where(['status'=>1])->all();
//        RoomsItem::deleteAll(['rooms_id' => $this->id]);
        foreach ($this->langs as $lang_id => $lang_data){
            $newsLang = NewsLang::find()
                ->where([
                    'news_id' => $this->id,
                    'lang_id' => $lang_id,
                ])
                ->one();
            if($newsLang == null){
                $newsLang = new NewsLang();
                $newsLang->news_id = $this->id;
                $newsLang->lang_id = $lang_id;
            }
            $newsLang->title = $lang_data['title'];
            $newsLang->text = $lang_data['text'];
            $newsLang->exerpt = $lang_data['exerpt'];
            $newsLang->seo_title = $lang_data['seo_title'];
            $newsLang->seo_desc = $lang_data['seo_desc'];
            $newsLang->save();
        }

        if($this->main_img != ''){
            $img = $this->getImageByName('main_img');
            if($img){
                $this->removeImageNoDel($img);
            }
            $this->attachImageNotUpload($this->main_img, $isMain = false, $name = 'main_img');
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->langs = $this->textsaray;
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

}
